version: '3'

services:
  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=sqlite:///beauty_shop.db
    volumes:
      - .:/app
    restart: always
